# Generated by Django 6.0 on 2025-12-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('puntaje', models.IntegerField(default=0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
            ],
        ),
    ]
